export const cities = [
  { name: "Stuart, FL", slug: "asphalt-paving-company-stuart-fl" },
  { name: "West Palm Beach, FL", slug: "asphalt-paving-company-west-palm-beach-fl" },
  { name: "Delray Beach, FL", slug: "asphalt-paving-company-deray-beach-fl" },
  { name: "Jupiter, FL", slug: "asphalt-paving-company-jupiter-fl" },
  { name: "Boca Raton, FL", slug: "asphalt-paving-company-boca-raton-fl" },
  { name: "Deerfield Beach, FL", slug: "asphalt-paving-company-deerfield-beach-fl" },
  { name: "Palm City, FL", slug: "asphalt-paving-company-palm-city-fl" },
  { name: "Pompano Beach, FL", slug: "asphalt-paving-company-pompano-beach-fl" },
  { name: "Wellington, FL", slug: "asphalt-paving-company-wellington-fl" },
  { name: "Tequesta, FL", slug: "asphalt-paving-company-tequesta-fl" },
  { name: "Port St. Lucie, FL", slug: "asphalt-paving-company-port-st-lucie-fl" },
  { name: "Parkland, FL", slug: "asphalt-paving-company-parkland-fl" },
  { name: "Palm Beach, FL", slug: "asphalt-paving-company-palm-beach-fl" },
  { name: "Palm Beach Gardens, FL", slug: "asphalt-paving-company-palm-beach-gardens-fl" },
  { name: "North Palm Beach, FL", slug: "asphalt-paving-company-north-palm-beach-fl" },
  { name: "Loxahatchee, FL", slug: "asphalt-paving-company-loxahatchee-fl" },
  { name: "Lantana, FL", slug: "asphalt-paving-company-lantana-fl" },
  { name: "Fort Lauderdale, FL", slug: "fort-lauderdale-fl" },
  { name: "Lake Worth, FL", slug: "asphalt-paving-company-lake-worth-fl" },
  { name: "Juno Beach, FL", slug: "asphalt-paving-company-juno-beach-fl" },
  { name: "Fort Pierce, FL", slug: "asphalt-paving-company-fort-pierce-fl" },
  { name: "Boynton Beach, FL", slug: "asphalt-paving-company-boynton-beach-fl" },
] as const;

export const extraServiceCities = [
  "Palm City, FL",
  "Jensen Beach, FL",
  "Port St. Lucie, FL",
  "Hobe Sound, FL",
  "Stuart, FL",
  "Jupiter, FL",
  "Juno Beach, FL",
  "Lantana, FL",
  "Tequesta, FL",
  "Palm Beach Gardens, FL",
  "West Palm Beach, FL",
  "Lake Worth, FL",
  "Loxahatchee, FL",
  "Palm Beach, FL",
  "Boca Raton, FL",
  "Pompano Beach, FL",
  "Delray Beach, FL",
  "North Palm Beach, FL",
  "Boynton Beach, FL",
  "Deerfield Beach, FL",
  "Hollywood, FL",
  "Fort Pierce, FL",
  "Coral Ridge, FL",
  "Weston, FL",
  "Dania Beach, FL",
  "Davie, FL",
  "Wellington, FL",
  "Parkland, FL",
  "Plantation, FL",
  "Fort Lauderdale, FL",
] as const;

export function cityBySlug(slug: string) {
  return cities.find((c) => c.slug === slug);
}
