export type GalleryCategory = "paving" | "sealcoating";

export const galleryImages: { src: string; alt: string; category: GalleryCategory }[] = [
  { src: "/gallery/paving/asphalt-parking-lot_1.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot_2.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot_3.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot_4.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot_5.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot_6.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot_7.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot_8.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/palm-trees-asphalt.jpg", alt: "Palm trees and asphalt", category: "paving" },
  { src: "/gallery/paving/dark-asphalt.jpg", alt: "Dark asphalt paving", category: "paving" },
  { src: "/gallery/paving/cloudy-sky-asphalt.jpg", alt: "Asphalt under cloudy sky", category: "paving" },
  { src: "/gallery/paving/asphalt-step-1.jpg", alt: "Asphalt paving step 1", category: "paving" },
  { src: "/gallery/paving/asphalt-step-2.jpg", alt: "Asphalt paving step 2", category: "paving" },
  { src: "/gallery/paving/asphalt-step-3.jpg", alt: "Asphalt paving step 3", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot.jpg", alt: "Finished asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/apartment-roads.jpg", alt: "Apartment community roads", category: "paving" },
  { src: "/gallery/paving/rolling-driveway.jpg", alt: "Rolling asphalt driveway", category: "paving" },
  { src: "/gallery/paving/river-parking-lot.jpg", alt: "Parking lot near water", category: "paving" },
  { src: "/gallery/paving/paving-street.jpg", alt: "Street paving", category: "paving" },
  { src: "/gallery/paving/paving-half-of-street.jpg", alt: "Street paving in progress", category: "paving" },
  { src: "/gallery/paving/palm-tree-parking-lot.jpg", alt: "Palm tree parking lot", category: "paving" },
  { src: "/gallery/paving/house-long-driveway.jpg", alt: "Long residential driveway", category: "paving" },
  { src: "/gallery/paving/house-driveway.jpg", alt: "House driveway", category: "paving" },
  { src: "/gallery/paving/handicap-parking-lot.jpg", alt: "Accessible parking lot", category: "paving" },
  { src: "/gallery/paving/driveway.jpg", alt: "Residential driveway", category: "paving" },
  { src: "/gallery/paving/community-street.jpg", alt: "Community street", category: "paving" },
  { src: "/gallery/paving/church-parking-lot-arrows.jpg", alt: "Church parking lot arrows", category: "paving" },
  { src: "/gallery/paving/church-parking-lot.jpg", alt: "Church parking lot", category: "paving" },
  { src: "/gallery/paving/building-parking-lot.jpg", alt: "Building parking lot", category: "paving" },
  { src: "/gallery/paving/Parking-Lot-1.jpg", alt: "Commercial parking lot", category: "paving" },
  { src: "/gallery/paving/Parking-Lot-2.jpg", alt: "Commercial parking lot", category: "paving" },
  { src: "/gallery/paving/Parking-Lot-3.jpg", alt: "Commercial parking lot", category: "paving" },
  { src: "/gallery/paving/asphalt_1.jpg", alt: "Asphalt paving", category: "paving" },
  { src: "/gallery/paving/asphalt_2.jpg", alt: "Asphalt paving", category: "paving" },
  { src: "/gallery/paving/business-parking-lot.jpg", alt: "Business parking lot", category: "paving" },
  { src: "/gallery/paving/parking-lot-with-lines.jpg", alt: "Parking lot with lines", category: "paving" },
  { src: "/gallery/paving/paving-parking-lot.jpg", alt: "Paving a parking lot", category: "paving" },
  { src: "/gallery/paving/large-parking-lot.jpg", alt: "Large parking lot", category: "paving" },
  { src: "/gallery/paving/construction-site-street.jpg", alt: "Construction site street", category: "paving" },
  { src: "/gallery/paving/business-asphalt.jpg", alt: "Business asphalt", category: "paving" },
  { src: "/gallery/paving/before-parking-lot.jpg", alt: "Parking lot before paving", category: "paving" },
  { src: "/gallery/paving/brick-ashalt-parking-lot.jpg", alt: "Parking lot with brick", category: "paving" },
  { src: "/gallery/paving/new-parking-lot.jpg", alt: "New parking lot", category: "paving" },
  { src: "/gallery/paving/parking-lot-set-up.jpg", alt: "Parking lot setup", category: "paving" },
  { src: "/gallery/paving/asphalt-parking-lot-1.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/Pave-roadway.jpg", alt: "Paved roadway", category: "paving" },
  { src: "/gallery/paving/paved-parking-lot.jpg", alt: "Paved parking lot", category: "paving" },
  { src: "/gallery/paving/Paved-Apartment-complex.jpg", alt: "Paved apartment complex", category: "paving" },
  { src: "/gallery/paving/Palms-and-Pavement.jpg", alt: "Palms and pavement", category: "paving" },
  { src: "/gallery/paving/House-pic-after.jpg", alt: "House after paving", category: "paving" },
  { src: "/gallery/paving/Duplex-photo.jpg", alt: "Duplex driveway", category: "paving" },
  { src: "/gallery/paving/Asphalt-Parking-Lot.jpg", alt: "Asphalt parking lot", category: "paving" },
  { src: "/gallery/paving/House-Driveway.jpg", alt: "House driveway", category: "paving" },
  { src: "/gallery/paving/Twin-Peaks.jpg", alt: "Twin Peaks parking lot", category: "paving" },
  { src: "/gallery/paving/3rd-pic-in-prep-do-row-3-1st-pic-finish-job.jpg", alt: "Paving job in progress", category: "paving" },
  { src: "/gallery/paving/1st-pic-5th-row-then-yellow-dump-2nd.jpg", alt: "Asphalt crew and dump truck", category: "paving" },
  { src: "/gallery/paving/second-row-last-pic.jpg", alt: "Finished paving work", category: "paving" },
  { src: "/gallery/paving/second-row-2nd-pic.jpg", alt: "Paving work", category: "paving" },
  { src: "/gallery/paving/asphalt-gallery-1st-roll-2nd-pic.jpg", alt: "Asphalt roller", category: "paving" },
  { src: "/gallery/paving/Unknown.jpg", alt: "Paving project", category: "paving" },
  { src: "/gallery/paving/Unknown-1.png", alt: "Paving project", category: "paving" },
  { src: "/gallery/paving/Unknown-2.jpg", alt: "Paving project", category: "paving" },
  { src: "/gallery/paving/Unknown-3.png", alt: "Paving project", category: "paving" },
  { src: "/gallery/paving/Unknown-4.jpg", alt: "Paving project", category: "paving" },
  { src: "/gallery/paving/Unknown-5.jpg", alt: "Paving project", category: "paving" },
  { src: "/gallery/paving/6788481311683810014.jpg", alt: "Completed paving work", category: "paving" },
  { src: "/gallery/paving/6788481311683810014-1.jpg", alt: "Completed paving work", category: "paving" },
  { src: "/gallery/paving/Screenshot_20250905_092505_Messages.jpg", alt: "Customer project photo", category: "paving" },
  { src: "/gallery/paving/Screenshot_20250906_164534_Messages.jpg", alt: "Customer project photo", category: "paving" },
  { src: "/gallery/paving/Screenshot_20250906_164543_Messages.jpg", alt: "Customer project photo", category: "paving" },
  { src: "/gallery/paving/Screenshot_20250906_164547_Messages.jpg", alt: "Customer project photo", category: "paving" },
  { src: "/gallery/paving/Screenshot_20251015_200124_Gallery.jpg", alt: "Customer project photo", category: "paving" },
  { src: "/gallery/paving/Screenshot_20260615_162903_Messages.jpg", alt: "Customer project photo", category: "paving" },
  { src: "/gallery/paving/Screenshot_20260615_162903_Messages-1.jpg", alt: "Customer project photo", category: "paving" },
  { src: "/gallery/sealcoating/sealcoating_1.jpg", alt: "Seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/sealcoating_2.jpg", alt: "Seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/sealcoating_3.jpg", alt: "Seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/seat-coat-parking.jpg", alt: "Seal coated parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/seal-coat-with-no-cars.jpg", alt: "Seal coat without cars", category: "sealcoating" },
  { src: "/gallery/sealcoating/seal-coat-with-cars.jpg", alt: "Seal coat with cars", category: "sealcoating" },
  { src: "/gallery/sealcoating/seal-coat-out.jpg", alt: "Seal coating application", category: "sealcoating" },
  { src: "/gallery/sealcoating/seal-coat-in-out.jpg", alt: "Seal coating in and out", category: "sealcoating" },
  { src: "/gallery/sealcoating/apartment-complex-sealcoat.jpg", alt: "Apartment complex sealcoat", category: "sealcoating" },
  { src: "/gallery/sealcoating/apartment-complex-sealcoat-2.jpg", alt: "Apartment complex sealcoat", category: "sealcoating" },
  { src: "/gallery/sealcoating/dealership-seal-coating.jpg", alt: "Dealership seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/dealership-roads.jpg", alt: "Dealership roads", category: "sealcoating" },
  { src: "/gallery/sealcoating/dealership-parking-lot.jpg", alt: "Dealership parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/arbys-parking-lot.jpg", alt: "Arby's parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/Badcock-furniture-parking-lot.jpg", alt: "Badcock furniture parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/bank-of-america-parking-lot.jpg", alt: "Bank of America parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/chilis-parking-lot.jpg", alt: "Chili's parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/driveway-seal-coat.jpg", alt: "Driveway seal coat", category: "sealcoating" },
  { src: "/gallery/sealcoating/driveway-seal-coating.jpg", alt: "Driveway seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/hampton-parking-lot.jpg", alt: "Hampton Inn parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/ihop-parking-lot.jpg", alt: "IHOP parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/long-driveway-seal-coating.jpg", alt: "Long driveway seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/neighborhood-road-seal-coating.jpg", alt: "Neighborhood road seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/parking-lot-seal-coating.jpg", alt: "Parking lot seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/pbs-entrance.jpg", alt: "Property entrance seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/road-seal-coating.jpg", alt: "Road seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/seal-coating-road.jpg", alt: "Seal coating road", category: "sealcoating" },
  { src: "/gallery/sealcoating/shopping-parking-lot.jpg", alt: "Shopping parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/street-road-seal-coat.jpg", alt: "Street seal coat", category: "sealcoating" },
  { src: "/gallery/sealcoating/street-seal-coating.jpg", alt: "Street seal coating", category: "sealcoating" },
  { src: "/gallery/sealcoating/taco-bell-parking-lot.jpg", alt: "Taco Bell parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/walgreens-parking-lot.jpg", alt: "Walgreens parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/applebees-parking-lot.jpg", alt: "Applebee's parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/Apartment-Complex.jpg", alt: "Apartment complex", category: "sealcoating" },
  { src: "/gallery/sealcoating/Church-Parking-Lot.jpg", alt: "Church parking lot", category: "sealcoating" },
  { src: "/gallery/sealcoating/unnamed-1-1.jpg", alt: "Seal coating project", category: "sealcoating" },
];
