export const referralGroups = [
  {
    title: "Residential Communities",
    items: [
      "Palm Bay Villas",
      "Presidential Golfview HOA",
      "Boca Raton Harbor",
      "Charolais Villas",
      "Crystal Point HOA",
      "Boca Terr Condos Assoc",
      "Yacht Club Condo Assoc",
      "May Fair House HOA",
      "Oak Wood Lakes HOA",
      "Rolling Golf & Tennis Club Condos",
      "Palm Beach Shores Apts",
      "Tavares Cove",
      "Lands of the Presidents HOA",
      "The Landings of Lake Worth HOA",
      "Barnett Square Condo HOA",
    ],
  },
  {
    title: "General Contractors",
    items: [
      "West Contruction Inc.",
      "Clark Construction",
      "C.D.L.",
      "Danella Construction",
      "Rolyn Companies Inc.",
      "J.M.W. Construction",
      "Purdy Construction",
      "K & M Construction",
      "Mullings Engineering Construction",
      "Creative Contractors",
      "Everglade General Contracting",
      "GCG Contracting",
    ],
  },
  {
    title: "Commercial",
    items: [
      "Mid County Service Center",
      "Auto Mall",
      "IHOP",
      "Walgreens",
      "Hampton Inn Hotels",
      "Ramada Inn Hotel",
      "Bank of America",
      "Suntrust Bank Flagler Square",
      "America Legion",
      "FED X",
      "Taco Bell",
      "Arby’s",
      "Applebee’s",
      "Synous Bank",
      "Twin Peaks",
    ],
  },
  {
    title: "Property Management Co.",
    items: [
      "Green Park Management LLC.",
      "Ruby Rinker Inc.",
      "Tromans MMJ. Inc.",
      "Custom Property MGN. Inc.",
      "Frima Management Group",
      "Complete Property Management",
      "Pentaur Properties",
      "DMB Flordia Restaurant Group",
      "Lane Valente",
      "Designs To Go",
    ],
  },
  {
    title: "County Parks",
    items: [
      "Lake Ida Park",
      "Willson Park",
      "Jupiter Farms Park",
      "District Park",
      "Palm Beach Shores Park",
      "Burt Reynolds Park",
      "Phil Foster Park",
    ],
  },
  {
    title: "Churches",
    items: [
      "Royal Palm Presbyterian",
      "Unity in the Pines",
      "Church in the Gardens",
      "Christ Fellowship",
      "Pentecostal Tabernacle",
      "Trinty Christ Academy",
      "Bethel Baptist",
      "St. Paul Church",
      "Av-angel Assembly",
      "Beloved Victory Church",
      "New Bethel Baptist Church",
    ],
  },
  {
    title: "Schools Districts",
    items: [
      "Santaluces Highschool",
      "Omminie School",
      "Roosevelt Highschool",
      "Christa Mcauliffe Middle School",
      "Jupiter Farms Elementary School",
    ],
  },
] as const;
